version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  initial-step:
    machine:
      enabled: true
    steps:
      - run: 
          name: Create a folder
          command: |
            mkdir dist
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - run: npm run build-ci
  deploy:
    machine:
      enabled: true
    steps:
      - run: 
          name: Deploy Over SSH
          command: |
            pwd
      - run: 
          name: Deploy Over SSH
          command: |
            ls
      - run: 
          name: Deploy Over SSH
          command: |
            scp -P 7822 -r dist/* ttuz@nl1-ls2.a2hosting.com:/tt.uz/
workflows:
   build-and-deploy:
     jobs:
       - initial-step
       - build-and-test:
           requires:
             - initial-step # only deploy once build job has completed
       - deploy:
           requires:
             - build-and-test # only deploy once build job has completed
           filters:
             branches:
               only: master # only deploy on the master branch



               