version: 2.1
jobs:
  build-and-test:
    working_directory: ~/project
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "6d:5d:3b:88:05:6c:4c:bb:cd:58:3a:c2:25:57:ff:a7"
      - run:
          name: Install
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run: 
          name: Deploy Over SSH
          command: |
            ssh -o StrictHostKeyChecking=no -p 7822 $SSH_USER@$SSH_HOST 'exit'
      - run: 
          name: Deploy Over SSH
          command: |
            scp -P 7822 -r ./dist/* ttuz@nl1-ls2.a2hosting.com:./test/
workflows:
   build-and-deploy:
     jobs:
       - build-and-test:
           filters:
             branches:
               only: master # only deploy on the master branch